import pytest
import asyncio
from pydantic import ValidationError
from dualscale_solver.numeric.phase12_autoresearch_problems import (
    AerospaceScramjetMitigation,
    MedicalVADRotorDynamics,
    HyperscaleWindFarmSteering,
    AutomotiveBTMSMicroChannels,
    NuclearTokamakDisruption,
    solve_scramjet_sbli_mitigation,
)
from dualscale_solver.agents.phase12_workflow_orchestrator import run_phase12_pipeline
from dualscale_solver.agents.auto_research_loop import KarpathyAutoResearchLoop
import unittest.mock

@pytest.fixture(autouse=True)
def mock_huggingface_datasets():
    """Mock datasets.load_dataset to prevent network calls and HDF5 parsing errors in CI."""
    with unittest.mock.patch("dualscale_solver.numeric.phase12_autoresearch_problems.load_dataset") as mock_load:
        # Realistic snapshot matching expected HF dataset schema
        dummy_data = [{
            "velocity": [0.1, 0.2, 0.1],
            "magnetic_field": [0.05, 0.05, 0.05],
            "plasma_beta": 0.05,
            "Mach": 2.0,
            "viscosity": 3.5e-3,
        }]
        mock_load.return_value = dummy_data
        yield mock_load


# ---------------------------------------------------------------------------
# H66-H70 Pydantic invariant model tests (pass/fail)
# ---------------------------------------------------------------------------

def test_h66_aerospace_scramjet_mitigation_pass():
    model = AerospaceScramjetMitigation(
        status="CERTIFIED",
        sbli_prediction_horizon_ms=6.0,
        unstart_prevented=True,
        actuation_latency_ms=0.5
    )
    assert model.verify_h66() is True

def test_h66_aerospace_scramjet_mitigation_fail():
    model = AerospaceScramjetMitigation(
        status="FAILED",
        sbli_prediction_horizon_ms=4.0,  # Below 5.0
        unstart_prevented=True,
        actuation_latency_ms=0.5
    )
    assert model.verify_h66() is False

def test_h67_medical_vad_rotor_pass():
    model = MedicalVADRotorDynamics(
        status="CERTIFIED",
        max_shear_stress_pa=140.0,
        thrombosis_stagnation_zones=0,
        hemolysis_index_reduction_pct=60.0
    )
    assert model.verify_h67() is True

def test_h67_medical_vad_rotor_fail():
    model = MedicalVADRotorDynamics(
        status="FAILED",
        max_shear_stress_pa=160.0,  # Above 150
        thrombosis_stagnation_zones=0,
        hemolysis_index_reduction_pct=60.0
    )
    assert model.verify_h67() is False

def test_h68_hyperscale_wind_farm_pass():
    model = HyperscaleWindFarmSteering(
        status="CERTIFIED",
        turbines_simulated=1024,
        wake_deflection_angle_deg=10.0,
        power_yield_increase_pct=20.0
    )
    assert model.verify_h68() is True

def test_h69_automotive_btms_pass():
    model = AutomotiveBTMSMicroChannels(
        status="CERTIFIED",
        fractal_generations=4,
        pressure_drop_reduction_pct=25.0,
        heat_transfer_increase_pct=35.0
    )
    assert model.verify_h69() is True

def test_h70_nuclear_tokamak_pass():
    model = NuclearTokamakDisruption(
        status="CERTIFIED",
        plasma_beta=0.08,
        holographic_bound_satisfied=True,
        disruption_prediction_horizon_ms=15.0
    )
    assert model.verify_h70() is True


# ---------------------------------------------------------------------------
# Orchestrator convergence (full pipeline)
# ---------------------------------------------------------------------------

def test_phase12_orchestrator_convergence():
    report = run_phase12_pipeline()
    assert report["certificate"]["overall_status"] == "CERTIFIED"
    assert report["certificate"]["problems_converged"]["H66_aerospace_scramjet"] is True

    # All loops must converge to CERTIFIED status
    for loop_name, loop_res in report["loops"].items():
        assert loop_res["final_status"] == "CERTIFIED", (
            f"{loop_name} did not converge: {loop_res['best_result']}"
        )
        # Must have run at least 1 real iteration
        assert loop_res["iterations_run"] >= 1, f"{loop_name} ran 0 iterations"
        # Ratchet: best_fitness must be present and positive
        assert loop_res["best_fitness"] > 0, f"{loop_name} best_fitness={loop_res['best_fitness']}"

    # SHA-256 must be unique per run (includes timestamp) and non-trivial
    cert_hash = report["certificate"]["sha256_hash"]
    assert len(cert_hash) == 64, "SHA-256 must be a 64-hex-char string"
    assert cert_hash != "0" * 64, "SHA-256 must not be trivially zero"


# ---------------------------------------------------------------------------
# Negative controls
# ---------------------------------------------------------------------------

def test_negative_control_invalid_status():
    """NC-P12-01: Auto-Research fails if an invalid status is generated by the LLM."""
    with pytest.raises(ValidationError):
        AerospaceScramjetMitigation(
            status="HALLUCINATED_STATUS",
            sbli_prediction_horizon_ms=6.0,
            unstart_prevented=True,
            actuation_latency_ms=0.5
        )


# ---------------------------------------------------------------------------
# Boundary conditions at exact thresholds
# ---------------------------------------------------------------------------

def test_h66_boundary_sbli_horizon_exactly_at_limit():
    """Horizon == 5.0 must PASS (>= 5.0 inclusive)."""
    model = AerospaceScramjetMitigation(
        status="CERTIFIED", sbli_prediction_horizon_ms=5.0,
        unstart_prevented=True, actuation_latency_ms=1.0
    )
    assert model.verify_h66() is True


def test_h66_boundary_latency_just_over_limit():
    """Latency 1.001 ms must FAIL (> 1.0)."""
    model = AerospaceScramjetMitigation(
        status="FAILED", sbli_prediction_horizon_ms=6.0,
        unstart_prevented=True, actuation_latency_ms=1.001
    )
    assert model.verify_h66() is False


def test_h67_boundary_shear_just_below_limit():
    """Shear 149.99 Pa must PASS (< 150)."""
    model = MedicalVADRotorDynamics(
        status="CERTIFIED", max_shear_stress_pa=149.99,
        thrombosis_stagnation_zones=0, hemolysis_index_reduction_pct=46.0
    )
    assert model.verify_h67() is True


def test_h67_boundary_shear_at_limit():
    """Shear exactly 150.0 Pa must FAIL (not strictly < 150)."""
    model = MedicalVADRotorDynamics(
        status="FAILED", max_shear_stress_pa=150.0,
        thrombosis_stagnation_zones=0, hemolysis_index_reduction_pct=46.0
    )
    assert model.verify_h67() is False


# ---------------------------------------------------------------------------
# Missing negative controls for H68, H69, H70
# ---------------------------------------------------------------------------

def test_h68_hyperscale_wind_farm_fail_turbines():
    """NC-P12-02: Too few turbines must FAIL H68."""
    model = HyperscaleWindFarmSteering(
        status="FAILED", turbines_simulated=999,
        wake_deflection_angle_deg=10.0, power_yield_increase_pct=20.0
    )
    assert model.verify_h68() is False


def test_h68_hyperscale_wind_farm_fail_yield():
    """NC-P12-03: Yield below 15% must FAIL H68."""
    model = HyperscaleWindFarmSteering(
        status="FAILED", turbines_simulated=1024,
        wake_deflection_angle_deg=10.0, power_yield_increase_pct=14.99
    )
    assert model.verify_h68() is False


def test_h69_automotive_btms_fail_gens():
    """NC-P12-04: Fewer than 3 fractal generations must FAIL H69."""
    model = AutomotiveBTMSMicroChannels(
        status="FAILED", fractal_generations=2,
        pressure_drop_reduction_pct=25.0, heat_transfer_increase_pct=35.0
    )
    assert model.verify_h69() is False


def test_h69_automotive_btms_fail_heat():
    """NC-P12-05: Heat transfer below 30% must FAIL H69."""
    model = AutomotiveBTMSMicroChannels(
        status="FAILED", fractal_generations=4,
        pressure_drop_reduction_pct=25.0, heat_transfer_increase_pct=29.99
    )
    assert model.verify_h69() is False


def test_h70_nuclear_tokamak_fail_beta():
    """NC-P12-06: Plasma beta <= 0.05 must FAIL H70."""
    model = NuclearTokamakDisruption(
        status="FAILED", plasma_beta=0.05,
        holographic_bound_satisfied=True, disruption_prediction_horizon_ms=15.0
    )
    assert model.verify_h70() is False


def test_h70_nuclear_tokamak_fail_holo():
    """NC-P12-07: Holographic bound not satisfied must FAIL H70."""
    model = NuclearTokamakDisruption(
        status="FAILED", plasma_beta=0.08,
        holographic_bound_satisfied=False, disruption_prediction_horizon_ms=15.0
    )
    assert model.verify_h70() is False


# ===========================================================================
# NEW: Karpathy Ratchet Architecture Tests
# ===========================================================================

def test_ratchet_monotonic_fitness():
    """The ratchet must guarantee that best_fitness never decreases across iterations."""
    report = run_phase12_pipeline()
    for loop_name, loop_res in report["loops"].items():
        history = loop_res["history"]
        best_seen = -float("inf")
        for entry in history:
            recorded_best = entry["best_fitness"]
            assert recorded_best >= best_seen, (
                f"[{loop_name}] Ratchet violated: best_fitness decreased from "
                f"{best_seen} to {recorded_best} at iteration {entry['iteration']}"
            )
            best_seen = recorded_best


def test_diagnostic_present_in_all_roms():
    """Every sim_result in every loop history must have a non-empty diagnostic string."""
    report = run_phase12_pipeline()
    for loop_name, loop_res in report["loops"].items():
        for entry in loop_res["history"]:
            diag = entry.get("diagnostic", "")
            assert isinstance(diag, str) and len(diag) > 10, (
                f"[{loop_name}] Iteration {entry['iteration']} has missing/empty diagnostic: '{diag}'"
            )


def test_ratchet_decision_present():
    """Every history entry must have a ratchet_decision of KEEP or REVERT."""
    report = run_phase12_pipeline()
    for loop_name, loop_res in report["loops"].items():
        for entry in loop_res["history"]:
            assert entry["ratchet_decision"] in ("KEEP", "REVERT"), (
                f"[{loop_name}] Invalid ratchet_decision: {entry['ratchet_decision']}"
            )


def test_eval_timing_budget():
    """Each ROM evaluation must complete in < 100ms (lightweight spectral kernel)."""
    report = run_phase12_pipeline()
    for loop_name, loop_res in report["loops"].items():
        for entry in loop_res["history"]:
            eval_ms = entry.get("eval_time_ms", 999)
            assert eval_ms < 100.0, (
                f"[{loop_name}] ROM evaluation took {eval_ms}ms (budget: <100ms) "
                f"at iteration {entry['iteration']}"
            )


def test_fitness_score_positive_on_convergence():
    """All converged loops must have a positive best_fitness in the final report."""
    report = run_phase12_pipeline()
    for loop_name, loop_res in report["loops"].items():
        if loop_res["final_status"] == "CERTIFIED":
            assert loop_res["best_fitness"] > 0, (
                f"[{loop_name}] CERTIFIED but best_fitness={loop_res['best_fitness']} <= 0"
            )


def test_temperature_breaker_detection():
    """Verify the temperature breaker logic: after 3 stagnant iterations, stuck flag is set."""
    # Build a synthetic history with 3 stagnant entries
    from dualscale_solver.agents.phase12_workflow_orchestrator import _aero_hypothesis

    # Simulate 3 iterations that all failed to improve
    stagnant_history = []
    for i in range(3):
        stagnant_history.append({
            "iteration": i + 1,
            "hypothesis": {"spectral_filter_coef": 2.0 + i * 0.1},
            "sim_result": {
                "sbli_horizon": 4.0,  # below target
                "unstart": False,
                "enstrophy": 18.0,
            },
            "fitness_score": 3.0,  # same fitness = stagnation
            "ratchet_decision": "REVERT",
            "stuck_in_local_minimum": (i == 2),  # only last entry gets the flag
        })

    # When stuck_in_local_minimum is True, the generator should make a radical jump
    result = _aero_hypothesis(stagnant_history)
    delta = result["spectral_filter_coef"] - 2.2  # prev_coef was 2.2 (last hypothesis)
    assert delta >= 1.5, (
        f"Temperature breaker should cause radical jump (delta >= 1.5) but got delta={delta:.2f}"
    )
    assert "STUCK" in result.get("reasoning", "").upper() or "RADICAL" in result.get("reasoning", "").upper(), (
        f"Reasoning should mention stuck/radical but got: {result.get('reasoning', '')}"
    )


def test_couette_spearman_sweep_n20():
    """Verify that the 20-point Couette sweep evaluates with statistically significant rank correlation."""
    from dualscale_solver.numeric.phase12_autoresearch_problems import couette_spearman_sweep

    res = couette_spearman_sweep(n_points=20)
    assert res["n_points"] == 20
    assert len(res["rpms"]) == 20
    assert len(res["tau_exact"]) == 20
    assert len(res["tau_rom"]) == 20
    assert res["spearman_rho"] > 0.90
    assert res["statistically_significant"] is True
    assert res["p_value"] < 0.05

